package com.linkedin.gdmix.utils

/**
 * Constants used by data module.
 */
object Constants {

  val ACTIVE = "active"
  val AUC = "auc"
  val MSE = "mse"
  val AVRO = "avro"
  val AVRO_FORMAT = "com.databricks.spark.avro"
  val CONFIG_SPLITTER = ";"
  val COUNT = "count"
  val CROSS = "_gdmixcross_"
  val EVAL_SUMMARY_JSON = "evalSummary.json"
  val FLOAT = "float"
  val GLOBAL = "global"
  val GROUP_ID = "groupId"
  val INDICES = "indices"
  val LONG = "long"
  val LR_MODEL_CLASS = "com.linkedin.photon.ml.supervised.classification.LogisticRegressionModel"
  val MEANS = "means"
  val MODEL_ID = "modelId"
  val NAME = "name"
  val OUTER = "outer"
  val OFFSET = "offset"
  val PARTITION_ID = "partitionId"
  val PASSIVE = "passive"
  val PER_ENTITY_GROUP_COUNT = "perEntityGroupCount"
  val PER_ENTITY_TOTAL_SAMPLE_COUNT = "perEntityTotalSampleCount"
  val PREDICTION_SCORE = "predictionScore"
  val PREDICTION_SCORE_PER_COORDINATE = "predictionScorePerCoordinate"
  val PREDICTION_SCORE_TEMP = "predictionScoreTemp"
  val PREDICTION_SCORE_SUM = "predictionScoreSum"
  val RMSE = "rmse"
  val TERM = "term"
  val TFRECORD = "tfrecord"
  val TF_EXAMPLE = "Example"
  val TF_SEQUENCE_EXAMPLE = "SequenceExample"
  val UID = "uid"
  val UID_TEMP = "uidTemp"
  val VALUE = "value"
  val VALUES = "values"
  val VARIANCES = "variances"
}
