# This workflow will install Python dependencies, run gdmix end to end on movieLens data
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Gdmix movieLens workflow

on:
  push:
    branches-ignore:
      - master
jobs:
  testbox:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
    container:
      image: linkedin/gdmix-dev
    steps:  
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
    - name: Build gdmix-data jar 
      run: |
        ./gradlew shadowJar 
    - name: Install GDMix dependencies and Test with pytest
      run: |
        cd gdmix-trainer 
        python setup.py develop 
        pytest
        cd ../gdmix-workflow 
        python setup.py develop 
        pytest
        cd ..
    - name: Prepare movieLens data
      run: |
        python scripts/download_process_movieLens_data.py
    - name: MovieLens logistic regression workflow
      run: |
        python -m gdmixworkflow.main --config_path gdmix-workflow/examples/movielens-100k/lr-movieLens.yaml --jar_path build/gdmix-data-all_2.11/libs/gdmix-data-all_2.11-*.jar
    - name: MovieLens DeText workflow
      run: |
        python -m gdmixworkflow.main --config_path gdmix-workflow/examples/movielens-100k/detext-movieLens.yaml --jar_path build/gdmix-data-all_2.11/libs/gdmix-data-all_2.11-*.jar
